language: python

# use container-based travis-ci infrastructure
#sudo: false

# use legacy infrastructure
sudo: required

addons:
  hosts:
    # hostnames will be enlisted in /etc/hosts and resolved to 127.0.0.1
    - syn-rabbitmq
    - syn-mongo

matrix:
  include:
    - python: "2.7"
      env: PYTHON_BINARY="python2.7"
      before_install:
        - pip install virtualenv

    - python: "3.4"
      env: PYTHON_BINARY="python3.4"
      addons:
        apt:
          packages:
          - python3-setuptools
          - python3-dev

#    - python: "3.5"
#      env: PYTHON_BINARY="python3.5"
#      addons:
#        apt:
#          sources:
#          # apt source hosting Python3.5 and 3.6
#          - deadsnakes
#          packages:
#          # Travis-ci has a known issue with Python3.5 and 3.6
#          - python3.5
#          - python3-setuptools
#          - python3-dev
#
#    - python: "3.6"
#      env: PYTHON_BINARY="python3.6"
#      addons:
#        apt:
#          sources:
#          # apt source hosting Python3.5 and 3.6
#          - deadsnakes
#          packages:
#          # Travis-ci has a known issue with Python3.5 and 3.6
#          - python3.6
#          - python3-setuptools
#          - python3-dev

services:
  - docker

before_install:
  # deactivate Travis-CI Python3 VirtualEnv, as it conflicts with the launch.py one
  - deactivate

install:
  # mongodb section
  - docker pull mongo:3
  - docker run -d --name syn-mongo -p 27017:27017 mongo:3

  # rabbit mq section
  - docker pull rabbitmq:3
  - docker run -d --hostname syn-rabbitmq --name syn-rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
  - scripts/rabbitmq_config.sh

before_script:
  - sudo mkdir --mode=777 -p /var/log/synergy-scheduler
  - ${PYTHON_BINARY} launch.py install
  - ${PYTHON_BINARY} launch.py db --reset

script:
  - ${PYTHON_BINARY} launch.py test

branches:
  only:
    - master
    - 2.0
    - 2.1
