version: "3.5"

# TODO: add volume creation on the host for syn-mongo
# TODO: add volume to the syn-rabbit container
# TODO: add volume for synergy-scheduler settings/flow/context files
# TODO: add worker container

networks:
  syn-network:
    driver: bridge

services:
  syn-mongo:
    container_name: syn-mongo
    image: mongo:3
    ports:
      # HOST:CONTAINER
      - "27017:27017"
    networks:
      - syn-network
    volumes:
      - "/data/db:/data/db"
    restart: "unless-stopped"

  syn-rabbitmq:
    container_name: syn-rabbitmq
    image: rabbitmq:3-management
    ports:
      # HOST:CONTAINER
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    networks:
      - syn-network
    restart: "unless-stopped"

  syn-rabbitmq-config:
    # Container names are unique; once a custom name is specified, attempting to scale beyond 1 results in an error
    container_name: syn-rabbitmq-config
    build:
      context: ./scripts
      dockerfile: rabbitmq_config.dockerfile
    networks:
      - syn-network
    restart: "no"
    depends_on:
      - syn-rabbitmq

  synergy-scheduler:
    # Container names are unique; once a custom name is specified, attempting to scale beyond 1 results in an error
    container_name: synergy-scheduler
    image: mushkevych/synergy-scheduler:2.0
    ports:
      # HOST:CONTAINER
      - "0.0.0.0:5000:5000"
    networks:
      - syn-network
    restart: "unless-stopped"
    depends_on:
      - syn-mongo
      - syn-rabbitmq-config
